<?php
echo "<HTML>\n";
echo "<HEAD>\n";
echo "<TITLE>::Theme SimpleTech by MDesigns::</TITLE>\n";
echo "<!-- Copyright © 2003 Mtechnik Dot Net. All rights reserved. -->\n";
echo "<script language=\"javascript\" src=\"themes/SimpleTech/FADE.JS\"></script>\n";
echo "<SCRIPT LANGUAGE=\"JavaScript\">\n";
echo "<!--\n";
echo "\n";
echo "function newImage(arg) {\n";
echo "	if (document.images) {\n";
echo "		rslt = new Image();\n";
echo "		rslt.src = arg;\n";
echo "		return rslt;\n";
echo "	}\n";
echo "}\n";
echo "\n";
echo "function changeImages() {\n";
echo "	if (document.images && (preloadFlag == true)) {\n";
echo "		for (var i=0; i<changeImages.arguments.length; i+=2) {\n";
echo "			document[changeImages.arguments[i]].src = changeImages.arguments[i+1];\n";
echo "		}\n";
echo "	}\n";
echo "}\n";
echo "\n";
echo "var preloadFlag = false;\n";
echo "function preloadImages() {\n";
echo "	if (document.images) {\n";
echo "		Simple_over = newImage(\"themes/SimpleTech/images/SimpleTech-hd_12-over.gif\");\n";
echo "		preloadFlag = true;\n";
echo "	}\n";
echo "}\n";
echo "\n";
echo "// -->\n";
echo "</SCRIPT>\n";
echo "</HEAD>\n";
echo "<BODY BGCOLOR=#000000 leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\" ONLOAD=\"preloadImages();\"><script language=\"javascript\" src=\"themes/SimpleTech/liveclock.js\"></script>\n";
echo "\n";
echo "<TABLE WIDTH=100% BORDER=0 CELLPADDING=0 CELLSPACING=0>\n";
echo "	<TR>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=15 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=8 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=93 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=67 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=27 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=94 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=94 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=94 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=9 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=21 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=33 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=165 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=35 HEIGHT=1></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/spacer.gif\" WIDTH=15 HEIGHT=1></TD>\n";
echo "	</TR>\n";
echo "	<TR>\n";
echo "		<TD ROWSPAN=6>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_01.gif\" WIDTH=15 HEIGHT=183></TD>\n";
echo "		<TD COLSPAN=7>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_02.gif\" WIDTH=477 HEIGHT=9></TD>\n";
echo "		<TD ROWSPAN=6>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_03.gif\" WIDTH=9 HEIGHT=183></TD>\n";
echo "		<TD ROWSPAN=6 background=\"themes/SimpleTech/images/SimpleTech-hd_full.gif\" WIDTH=100% HEIGHT=183></TD>\n";
echo "		<TD COLSPAN=3>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_05.gif\" WIDTH=233 HEIGHT=9></TD>\n";
echo "		<TD ROWSPAN=6>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_06.gif\" WIDTH=15 HEIGHT=183></TD>\n";
echo "	</TR>\n";
echo "	<TR>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_07.gif\" WIDTH=8 HEIGHT=29></TD>\n";
echo "		<TD COLSPAN=6 background=\"themes/SimpleTech/images/SimpleTech-hd_slogan.gif\" WIDTH=469 HEIGHT=29><font size=\"1\" color=\"#FFFFFF\" face=\"arial\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bienvenid@ a $sitename,  $username</font></TD>\n";
echo "		<TD>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_09.gif\" WIDTH=33 HEIGHT=29></TD>\n";
echo "		<TD COLSPAN=2 background=\"themes/SimpleTech/images/SimpleTech-hd_time.gif\" WIDTH=200 HEIGHT=29><script language=\"javascript\"><!--\n";
echo "new LiveClock('verdana','1','#FFFFFF','#','<b>Hora: ','</b>','190','1','1','0','2','null');\n";
echo "//--></script></TD>\n";
echo "	</TR>\n";
echo "	<TR>\n";
echo "		<TD ROWSPAN=2>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_11.gif\" WIDTH=8 HEIGHT=113></TD>\n";
echo "		<TD COLSPAN=2>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_12.gif\" WIDTH=160 HEIGHT=91></TD>\n";
echo "		<TD COLSPAN=4>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_13.gif\" WIDTH=309 HEIGHT=91></TD>\n";
echo "		<TD COLSPAN=3>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_14.gif\" WIDTH=233 HEIGHT=91></TD>\n";
echo "	</TR>\n";
echo "	<TR>\n";
echo "		<TD COLSPAN=5 valign=bottom background=\"themes/SimpleTech/images/SimpleTech-hd_user.gif\" WIDTH=375 HEIGHT=22>$theuser<TD ROWSPAN=2>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_17.gif\" WIDTH=33 HEIGHT=46></TD>\n";
echo "		<TD COLSPAN=2>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_site.gif\" WIDTH=200 HEIGHT=22></TD>\n";
echo "	</TR>\n";
echo "	<TR>\n";
echo "		<TD ROWSPAN=2>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_19.gif\" WIDTH=8 HEIGHT=32></TD>\n";
echo "\n";
//<!-- Menu Config -->//
echo "\n";
echo "		<TD valign=bottom align=center background=\"themes/SimpleTech/images/SimpleTech-hd_b1.gif\" WIDTH=93 HEIGHT=24><a href=\"index.php\"><font size=\"1\" color=\"#FFFFFF\" face=\"arial\"><b>Inicio</b></font></a></TD>\n";
echo "		<TD valign=bottom align=center COLSPAN=2 background=\"themes/SimpleTech/images/SimpleTech-hd_b2.gif\" WIDTH=94 HEIGHT=24><a href=\"modules.php?name=Downloads\"><font size=\"1\" color=\"#FFFFFF\" face=\"arial\"><b>Descargas</b></a></font></TD>\n";
echo "		<TD valign=bottom align=center background=\"themes/SimpleTech/images/SimpleTech-hd_b3.gif\" WIDTH=94 HEIGHT=24><a href=\"modules.php?name=Forums\"><font size=\"1\" color=\"#FFFFFF\" face=\"arial\"><b>Foros</b></a></font></TD>\n";
echo "		<TD valign=bottom align=center background=\"themes/SimpleTech/images/SimpleTech-hd_b4.gif\" WIDTH=94 HEIGHT=24><a href=\"modules.php?name=Topics\"><font size=\"1\" color=\"#FFFFFF\" face=\"arial\"><b>Temas</b></a></font></TD>\n";
echo "		<TD valign=bottom align=center background=\"themes/SimpleTech/images/SimpleTech-hd_b5.gif\" WIDTH=94 HEIGHT=24><a href=\"modules.php?name=Web_Links\"><font size=\"1\" color=\"#FFFFFF\" face=\"arial\"><b>Enlaces</b></a></font></TD>\n";
echo "\n";
//<!-- End menu config -->//
echo "\n";
echo "		<TD align=left valign=bottom background=\"themes/SimpleTech/images/SimpleTech-hd_search.gif\" WIDTH=165 HEIGHT=24><form action=\"modules.php?op=modload&name=Search&file=index\" method=\"post\"><input type=\"text\" name=\"query\" value style=\"width:160;height:22;FONT-SIZE: 11px; color:#FFFFFF; background:#303030\"></TD>\n";
echo "		<TD align=center background=\"themes/SimpleTech/images/SimpleTech-hd_search2.gif\" WIDTH=35 HEIGHT=24><input type=\"image\" value=\"search\" src=\"themes/SimpleTech/images/go.gif\" border=\"0\"></TD></form>\n";
echo "	</TR>\n";
echo "	<TR>\n";
echo "		<TD COLSPAN=6>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_27.gif\" WIDTH=469 HEIGHT=8></TD>\n";
echo "		<TD COLSPAN=3>\n";
echo "			<IMG SRC=\"themes/SimpleTech/images/SimpleTech-hd_28.gif\" WIDTH=233 HEIGHT=8></TD>\n";
echo "	</TR>\n";
echo "</TABLE>\n";
echo "</BODY>\n";
echo "</HTML>\n";
?>
